<?php
/**
 * @file
 * stanford_subsites_admin_dash.module
 *
 * @author (s)
 *         Shea McKinney / sherakama
 *
 * @todo :::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 *
 *
 * :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 */

// Load Helper Module.
module_load_include('inc', 'stanford_subsites', 'stanford_subsites');


/**
 * Implements hook_help().
 */
function stanford_subsites_admin_dash_help($path, $arg) {
  switch ($path) {
    case 'admin/help#sws_admin_dash':
      return '<p>' . t('For more help please contact stanford web services: %email',
       array('%email' => 'help@stanford.edu')) . '</p>';
  }
  return;
}


/**
 * Implements hook_permission().
 */
function stanford_subsites_admin_dash_permission() {
  return array(
    'access sws admin dash' => array(
      'title' => t('Access Stanford Subsite Admin Dashboard'),
      'description' => t('See and use administration dashboard blocks'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stanford_subsites_admin_dash_menu($items = array()) {
  $items['admin/config/subsites/dashboard'] = array(
    'title' => 'Subsite administration dashboard',
    'page callback' => 'stanford_subsites_admin_dash_dashboard',
    'description' => 'An administration page for managing subsites and subsite content.',
    'access arguments' => array('access sws admin dash'),
    'type' => MENU_NORMAL_ITEM,
    'file' => "stanford_subsites_admin_dash.pages.inc",
  );
  return $items;
}

/**
 * Implements hook_views_api().
 */
function stanford_subsites_admin_dash_views_api() {
  return array("version" => "3.0");
}

/**
 * Implements hook_theme().
 */
function stanford_subsites_admin_dash_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['page_subsite_dashboard'] = array(
    'render element' => 'content',
    'base hook' => 'page',
    'template' => 'page--admin--config--subsites--dashboard',
    'path' => drupal_get_path('module', 'stanford_subsites_admin_dash') . '/templates',
   );
  return $theme;
}

////////////////////////////////////////////////////////////////////////////////
// BLOCKS       ////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

/**
 * Implements hook_block_info().
 */
function stanford_subsites_admin_dash_block_info() {

  $blocks['stanford_subsites_dashboard_banner'] = array(
    'info' => t('Subsite dashboard banner'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function stanford_subsites_admin_dash_block_view($delta = '') {
  $block = array();
  $subsite = node_load(stanford_subsites_get_subsite_workingspace());

  switch ($delta) {
    case 'stanford_subsites_dashboard_banner':
      $block['subject'] = check_plain($subsite->title);
      $block['title'] = "<none>";
      $block['content'] = stanford_subsites_dashboard_banner_block($subsite);
      break;


  }
  return $block;
}


/**
 * [stanford_subsites_dashboard_banner_block description]
 * @return [type] [description]
 */
function stanford_subsites_dashboard_banner_block($subsite) {

  $title = isset($subsite->title) ? check_plain($subsite->title) : t("All subsites");

  $content = "<h2 class=\"sooper-dooper-big-heading\">" . $title . "</h2>";
  $content .= "<p>" . t("You are currently managing %subsite_name. Change to", array("%subsite_name" => $title)) . ": </p>";

  $content .= drupal_render(drupal_get_form('stanford_subsite_working_space_jump_select_form'));

  return $content;
}

/**
 * Returns a select box with an option to select all the jumpstart blocks
 * @return [type] [description]
 */
function stanford_subsite_working_space_jump_select_form($form, $form_state, $subsite = NULL) {
  $form = array();
  $subsite = (!is_null($subsite)) ? $subsite : node_load(stanford_subsites_get_subsite_workingspace());

  $active_subsites = stanford_subsites_get_subsite_nodes();
  $options = array(0 => "-- " . t("All subsites") . " --");

  foreach ($active_subsites as $node) {
    $options[$node->nid] = $node->title;
  }

  $form['subsite_workingspace'] = array(
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => isset($subsite->nid) ? $subsite->nid : 0,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('change'),
  );

  return $form;
}

/**
 * [stanford_subsite_working_space_jump_select_form_submit description]
 * @param  [type] $form       [description]
 * @param  [type] $form_state [description]
 * @return [type]             [description]
 */
function stanford_subsite_working_space_jump_select_form_submit($form, $form_state) {
  $new_nid = check_plain($form_state['values']['subsite_workingspace']);
  stanford_subsites_set_subsite_workingspace($new_nid);
  drupal_set_message(t("Subsite working space has been changed"), "status");
}


