<?php
/**
 * @file
 * stanford_subsites_admin_dash.module
 *
 * @author (s)
 *         Shea McKinney / sherakama
 *
 * @todo :::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 *
 *
 * :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 */

// Load Helper Module.
module_load_include('inc', 'stanford_subsites', 'stanford_subsites');


/**
 * Implements hook_help().
 */
function stanford_subsites_admin_dash_help($path, $arg) {
  switch ($path) {
    case 'admin/help#sws_admin_dash':
      return '<p>' . t('For more help please contact stanford web services: %email',
       array('%email' => 'help@stanford.edu')) . '</p>';
  }
  return;
}


/**
 * Implements hook_permission().
 */
function stanford_subsites_admin_dash_permission() {
  return array(
    'access sws admin dash' => array(
      'title' => t('Access Stanford Subsite Admin Dashboard'),
      'description' => t('See and use administration dashboard blocks'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stanford_subsites_admin_dash_menu($items = array()) {

  $items['admin/config/subsites/dashboard'] = array(
    'title' => 'Manage Subsites',
    'page callback' => 'stanford_subsites_admin_dash_dashboard',
    'description' => 'An administration page for managing subsites and subsite content.',
    'access arguments' => array('access sws admin dash'),
    'type' => MENU_NORMAL_ITEM,
    'file' => "stanford_subsites_admin_dash.pages.inc",
    'menu_name' => "menu-subsite-dashboards",
    'expanded' => TRUE,
  );

  $items['admin/config/subsites/dashboard/all'] = array(
    'title' => 'All subsites',
    'page callback' => 'stanford_subsites_admin_dash_dashboard',
    'page arguments' => array("all"),
    'description' => 'An administration page for managing subsites and subsite content.',
    'access arguments' => array('access sws admin dash'),
    'type' => MENU_NORMAL_ITEM,
    'file' => "stanford_subsites_admin_dash.pages.inc",
    'menu_name' => "menu-subsite-dashboards",
  );

  $subsites = stanford_subsites_get_subsite_nodes();
  foreach ($subsites as $subsite) {
    $path = drupal_get_path_alias("node/" . $subsite->nid);
    $items['admin/config/subsites/dashboard/' . $path] = array(
      'title' => $subsite->{SUBSITE_NAME_FIELD}[$subsite->language][0]['value'],
      'page callback' => 'stanford_subsites_admin_dash_dashboard',
      'page arguments' => array($path),
      'description' => 'An administration page for managing subsites and subsite content.',
      'access arguments' => array('access sws admin dash'),
      'type' => MENU_NORMAL_ITEM,
      'file' => "stanford_subsites_admin_dash.pages.inc",
      'menu_name' => "menu-subsite-dashboards",
    );
  }

  return $items;
}

/**
 * Implements hook_views_api().
 */
function stanford_subsites_admin_dash_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_theme().
 */
function stanford_subsites_admin_dash_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['page_subsite_dashboard'] = array(
    'render element' => 'page',
    'base hook' => 'page',
    'template' => 'page--admin--config--subsites--dashboard',
    'path' => drupal_get_path('module', 'stanford_subsites_admin_dash') . '/templates',
  );
  return $theme;
}

////////////////////////////////////////////////////////////////////////////////
// BLOCKS       ////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

/**
 * Implements hook_block_info().
 */
function stanford_subsites_admin_dash_block_info() {

  $blocks['subsites_dashboard_banner'] = array(
    'info' => t('Subsite dashboard banner'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['subsites_dashboard_contexts'] = array(
    'info' => t('Subsite dashboard contexts'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['subsites_dashboard_blocks'] = array(
    'info' => t('Subsite dashboard blocks'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['subsites_dashboard_content'] = array(
    'info' => t('Subsite dashboard content'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['subsites_dashboard_create_new'] = array(
    'info' => t('Subsite dashboard create new'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['subsites_dashboard_edit_subs'] = array(
    'info' => t('Subsite dashboard edit subsite'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function stanford_subsites_admin_dash_block_view($delta = '') {
  $block = array();
  $subsite = "all";
  $nid = stanford_subsites_get_subsite_workingspace();
  if (is_numeric($nid)) {
    $subsite = node_load($nid);
  }

  switch ($delta) {
    case 'subsites_dashboard_banner':
      $block['subject'] = isset($subsite->title) ? check_plain($subsite->title) : $subsite;
      $block['title'] = "<none>";
      $block['content'] = stanford_subsites_dashboard_banner_block($subsite);
      break;

    case 'subsites_dashboard_contexts':
      $block['subject'] = t("Contexts");
      $block['title'] = t("Contexts");
      $block['content'] = stanford_subsites_dashboard_contexts_block($subsite);
      break;

    case 'subsites_dashboard_blocks':
      $block['subject'] = t("Blocks");
      $block['title'] = t("Blocks");
      $block['content'] = stanford_subsites_dashboard_blocks_block($subsite);
      break;

    case 'subsites_dashboard_content':
      $block['subject'] = t("Content");
      $block['title'] = t("Content");
      $block['content'] = stanford_subsites_dashboard_content_block($subsite);
      break;

    case 'subsites_dashboard_create_new':
      $block['subject'] = t("New");
      $block['title'] = t("New");
      $block['content'] = stanford_subsites_dashboard_create_new_block($subsite);
      break;

    case 'subsites_dashboard_edit_subs':
      $block['subject'] = t("Edit");
      $block['title'] = t("Edit");
      $block['content'] = stanford_subsites_dashboard_edit_subs_block($subsite);
      break;

  }
  return $block;
}


/**
 * [stanford_subsites_dashboard_banner_block description]
 * @return [type] [description]
 */
function stanford_subsites_dashboard_banner_block($subsite) {
  $content = "";
  $title = isset($subsite->title) ? check_plain($subsite->title) : t("All subsites");

  $content .= "<div class=\"inner-left\">";
    $content .= "<h2 class=\"sooper-dooper-big-heading\">" . $title . "</h2>";
    $content .= "<p>" . t("Subsite Dashboard") . "</p>";
  $content .= "</div>";

  return $content;
}

/**
 * [stanford_subsites_dashboard_contexts_block description]
 * @param  [type] $subsite [description]
 * @return [type]          [description]
 */
function stanford_subsites_dashboard_contexts_block($subsite) {
  $content = "";
  $contexts = stanford_subsites_admin_dash_get_subsite_contexts($subsite);
  $header = array(t("Name"), t("Description"), t("Paths"), t("Actions"));
  $rows = array();

  // In case we get "all" option.
  if (isset($subsite->nid)) {
    $index = stanford_subsite_index_get('nid', $subsite->nid);
    $alias = drupal_get_path_alias("node/" . $subsite->nid);
  }


  foreach ($contexts as $context_name => $context) {
    $paths = array();

    if (!isset($subsite->nid)) {
      $index = stanford_subsite_index_get('context', drupal_clean_css_identifier($context_name));
      if (isset($index->nid)) {
        $alias = drupal_get_path_alias("node/" . $index->nid);
      }
    }

    if (empty($index->nid)) {
      continue;
    }

    // If we have matching name and context then path up!
    if ($context->name == $index->context) {
      $paths[] = l($alias, $alias);
    }

    // Loop through the path conditions to gather paths.
    if (isset($context->conditions['path']['values'])) {
      foreach ($context->conditions['path']['values'] as $path) {
        if (stripos($path, $alias . "/") !== FALSE) {
          $paths[] = l($path, $path);
        }
      }
    }

    $list = array("items" => $paths);
    $path_list = theme('item_list', $list);
    $edit = l(t("Edit"), "admin/structure/context/list/" . $context->name . "/edit");
    $rows[]["data"] = array($context->name, $context->description, $path_list, $edit);
  }

  // Sort by title by default.
  uasort($rows, "stanford_subsites_dash_sort_blocks_rows_data");

  $limit = 10;
  pager_default_initialize(count($rows), $limit, 2);
  $page_get = isset($_GET['page']) ? check_plain($_GET['page']) : "0,0,0";
  $page_xp = explode(",", $page_get);
  $page = isset($page_xp[2]) ? $page_xp[2] : 0;

  $render_rows = array_slice($rows, $page, ($page + $limit));

  $table = array("header" => $header, "rows" => $render_rows);
  $content .= theme("table", $table);

  $args = array('quantity' => 6, "element" => 2);
  $content .= theme('pager', $args);

  return $content;
}

/**
 * [stanford_subsites_dashboard_blocks_block description]
 * @param  [type] $subsite [description]
 * @return [type]          [description]
 */
function stanford_subsites_dashboard_blocks_block($subsite) {
  $content = "";
  $contexts = stanford_subsites_admin_dash_get_subsite_contexts($subsite);

  // In case we get "all" option.
  if (isset($subsite->nid)) {
    $index = stanford_subsite_index_get('nid', $subsite->nid);
    $alias = drupal_get_path_alias("node/" . $subsite->nid);
  }

  $header = array(
    'title' => array('data' => t("Title"), 'type' => 'property', 'specifier' => 'name', 'sort' => 'desc'),
    'type' => array('data' => t("Type"), 'sort' => 'asc'),
    'context' => array('data' => t("Context")),
    'updated' => array('data' => t("Last Updated"), 'sort' => 'asc'),
    'author' => array('data' => t("Author"), 'sort' => 'asc'),
    'actions' => array('data' => t("Actions")),
  );
  $rows = array();

  global $theme;
  module_load_include("inc", "block", "block.admin");
  $blocks = block_admin_display_prepare_blocks($theme);

  foreach ($contexts as $context_name => $context) {

    // Only continue if we have blocks.
    if (!isset($context->reactions['block']['blocks'])) {
      continue;
    }

    if (!isset($subsite->nid)) {
      $index = stanford_subsite_index_get('context', drupal_clean_css_identifier($context_name));
      if (isset($index->nid)) {
        $alias = drupal_get_path_alias("node/" . $index->nid);
      }
    }

    if (empty($index->nid)) {
      continue;
    }

    foreach ($context->reactions['block']['blocks'] as $delta => $info) {
      $bean = NULL;
      $block = block_load($info['module'], $info['delta']);
      if ($info['module'] == "bean" && function_exists("bean_load_delta")) {
        $bean = bean_load_delta($info['delta']);
      }

      // Ok, titles are funky. Need to run through all this to get em.
      $title = isset($bean->label) ? $bean->label : FALSE;
      if ($title == FALSE) {
        $i = 0;
        while (isset($blocks[$i])) {
          if ($blocks[$i]['delta'] == $block->delta && $blocks[$i]['module'] == $block->module) {
            $title = check_plain($blocks[$i]['info']);
            break;
          }
          else {
            $title = t("Missing label");
          }
          $i++;
        }
      }

      $edit = isset($bean->type) ? l(t("Edit"), 'block/' . $bean->delta . '/edit') : l(t("Configure"), "admin/structure/block/manage/" . $info['module'] . "/" . $info['delta'] . "/configure");
      $configure = isset($bean->type) ? l(t("Configure"), "admin/structure/block/manage/" . $info['module'] . "/" . $info['delta'] . "/configure") : "";

      $rows[$delta]['title'] = $title;
      $rows[$delta]['type'] = isset($bean->type) ? $bean->type : "block";
      $rows[$delta]['context'][] = l(t($context->name), "admin/structure/context/list/" . $context->name . "/edit");
      $rows[$delta]['updated'] = isset($bean->changed) ? format_date($bean->changed, "small") : t("Not available");
      $rows[$delta]['author'] = isset($bean->changed) ? user_load($bean->uid)->name : t("Not available");
      $rows[$delta]['actions'] = $edit;

      if (!empty($configure)) {
        $rows[$delta]["actions"] .= " | " . $configure;
      }

    }

  }

  // Formatting again...
  foreach ($rows as $delta => &$info) {
    $info['context'] = theme("item_list", array("items" => $info["context"]));
  }

  // Sort by title by default.
  uasort($rows, "stanford_subsites_dash_sort_blocks_title");

  $limit = 10;
  pager_default_initialize(count($rows), $limit, 1);
  $page_get = isset($_GET['page']) ? check_plain($_GET['page']) : "0,0,0";
  $page_xp = explode(",", $page_get);
  $page = $page_xp[1];
  $min = ($page * $limit);
  $max = ($page * $limit) + $limit;
  $render_rows = array_slice($rows, $min, $max);

  $table = array("header" => $header, "rows" => $render_rows, 'empty' => t('Sorry, no results found'),);
  $content .= theme("table", $table);

  $args = array('quantity' => 6, "element" => 1);
  $content .= theme('pager', $args);

  return $content;
}

/**
 * Sort by block title.
 * @param  [type] $a [description]
 * @param  [type] $b [description]
 * @return [type]    [description]
 */
function stanford_subsites_dash_sort_blocks_title($a, $b) {
 return strcmp($a['title'], $b['title']);
}

function stanford_subsites_dash_sort_blocks_rows_data($a, $b) {
 return strcmp($a['data'][0], $b['data'][0]);
}

/**
 * Stanford manage content block.
 * @param  [type] $subsite [description]
 * @return [type]          [description]
 */
function stanford_subsites_dashboard_content_block($subsite) {
  $view = views_get_view('subsite_dashboard_manage_content');
  $content = "";

  // The $exposed_filters keys must correctly correspond with the actual keys of your view's exposed filters.
  $exposed_filters = array(
    'type' => 'All',
  );

  // Pass in exposed filter values. array_merge() order prioritizes user input.
  if (isset($view->exposed_input)) {
    $view->exposed_input = array_merge($exposed_filters, (array) $view->exposed_input);
    $view->exposed_raw_input = array_merge($exposed_filters, (array) $view->exposed_raw_input);
    $view->exposed_data = array_merge($exposed_filters, (array) $view->exposed_data);
  }

  // Only if we have a subsite.
  if (isset($subsite->nid)) {
    $tid = $subsite->{SUBSITE_TAGS_FIELD}[$subsite->language][0]['tid'];
    $view->set_arguments(array($tid));
    $view->set_display("block");
  }

  $content .= $view->preview();
  $view->destroy();

  return $content;
}

/**
 * Create new options block
 * @param  [type] $subsite [description]
 * @return [type]          [description]
 */
function stanford_subsites_dashboard_create_new_block($subsite) {
  $content = "";
  $vars = array();
  $items = array();
  $types = node_type_get_types();

  if ($subsite) {
    $term = _get_subsite_term_from_node($subsite);
  }

  // List out the available types of content that can/should go into a subsite.
  $enabled_types = variable_get('stanford_subsite_content_types', array());
  foreach ($enabled_types as $type) {

    if (!isset($types[$type])) {
      continue;
    }

    if (!empty($term)) {
      $items[] = l(t($types[$type]->name), "node/add/" . drupal_clean_css_identifier($type), array("query" => array(SUBSITE_TAGS_FIELD => $term->tid)));
    }
    else {
      $items[] = l(t($types[$type]->name), "node/add/" . drupal_clean_css_identifier($type));
    }


  }

  $vars['items'] = $items;
  $content = theme("item_list", $vars);

  return $content;
}

// /**
//  * [stanford_subsites_dashboard_working_space_quick_toggle description]
//  * @param  [type] $subsite [description]
//  * @return [type]          [description]
//  */
// function stanford_subsites_dashboard_working_space_quick_toggle($subsite) {
//   $content = "";

//   // Get and make some changes...
//   $form = drupal_get_form('stanford_subsite_working_space_jump_select_form');
//   unset($form['submit']);
//   $form['subsite_workingspace']['#title'] = t("Subsite toggle");
//   $form["#attached"]["js"][] = drupal_get_path("module", "stanford_subsites_admin_dash") . "/js/ws.quick.toggle.js";
//   $content .= drupal_render($form);

//   $css = "#block-stanford-subsites-admin-dash-subsites-dashboard-ws-toggle { display: inline-block; position: relative; vertical-align: bottom; }";
//   $css .= "#block-stanford-subsites-admin-dash-subsites-dashboard-ws-toggle form { padding: 0; margin: 0; }";
//   $css .= "#block-stanford-subsites-admin-dash-subsites-dashboard-ws-toggle .form-item { padding: 0; margin: 0; }";
//   $css .= "#block-stanford-subsites-admin-dash-subsites-dashboard-ws-toggle form label { font-size: 1em; margin: 0; padding: 0; }";
//   $css .= "#block-stanford-subsites-admin-dash-subsites-dashboard-ws-toggle form select { font-size: 1em; height: 1.5em; line-height: 1.5em; }";

//   drupal_add_css($css, "inline");

//   return $content;
// }

/**
 * Subsite options
 * @param  [type] $subsite [description]
 * @return [type]          [description]
 */
function stanford_subsites_dashboard_edit_subs_block($subsite) {

  if (empty($subsite) || $subsite == "all") {
    return "";
  }

  $content = "";
  $index = stanford_subsite_index_get('nid', $subsite->nid);
  $menu_name = $index->menu;
  $menu_url = "admin/structure/menu/manage/" . $menu_name;
  $edit_url = "node/" . $subsite->nid . "/edit";
  $vars = array();
  $items = array();

  $items[] = l(t("Menu"), $menu_url);
  $items[] = l(t("Settings"), $edit_url);

  $vars['items'] = $items;
  $content = theme("item_list", $vars);
  return $content;
}

/**
 * Returns a list of contexts filtered by the subsite of choice.
 * @param  [type] $subsite [description]
 * @return [type]          [description]
 */
function stanford_subsites_admin_dash_get_subsite_contexts($subsite) {
  $contexts = context_load();

  if (!isset($subsite->nid) || $subsite == "all") {
    return $contexts;
  }

  $nid = $subsite->nid;
  $alias = drupal_get_path_alias("node/" . $subsite->nid);

  foreach ($contexts as $context_name => $context) {
    $valid = FALSE;

    if (isset($context->conditions['active_subsite'])) {
      if (in_array($nid, $context->conditions['active_subsite']['values'])) {
        $valid = TRUE;
      }
    }

    if (isset($context->conditions['path'])) {
      foreach ($context->conditions['path']['values'] as $path) {
        if (strpos($path, $alias . "/") !== FALSE) {
          $valid = TRUE;
        }
      }
    }

    if (!$valid) {
      unset($contexts[$context_name]);
    }

  }

  return $contexts;
}


/**
 * Implements hook_context_load_alter().
 */
function stanford_subsites_admin_dash_context_load_alter(&$context) {
  $key = "stanford_jumpstart_admin_shortcuts";
  if ($context->name == $key) {
    $context->reactions["block"]['blocks']['menu-subsite-dashboards'] = array(
      "module" => "menu",
      "delta" => "menu-subsite-dashboards",
      "region" => "admin_shortcuts",
      "weight" => -5,
    );
  }
}
